Upgrade buildkite agent on macOS instead of install
If it's running in Buildkite, it already has the agent, by
definition. This just ensures we have the latest version of it.

Without this change, builds will fail with an error like this:

```
Error: buildkite-agent 3.13.2 is already installed
To upgrade to 3.14.0, run `brew upgrade buildkite-agent`.
```

Signed-off-by: Christopher Maier <cmaier@chef.io>