Don't panic in the unusual event persisting butterfly data takes over 30 s
The Duration type is unsigned, so subtracting a larger duration from a
smaller one causes this panic, observed in CI:

thread 'persist-e38384ae82144423ac70ec342e865997' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Change the calculation of our persist loop's wait time to use checked_sub
and if persist_data takes longer than our desired persist loop period, print a warning.

Thanks to to @stevendanna for surfacing this.

Signed-off-by: Jon Bauman <5906042+baumanj@users.noreply.github.com>