Update ipc-channel to latest version
The previously referenced commit doesn't exist in the `ipc-channel`
repo, resulting in an error when building:

```
root@vagrant:/src# cargo build --verbose
    Updating git repository `https://github.com/habitat-sh/ipc-channel`
error: failed to load source for a dependency on `ipc-channel`
Caused by:
  Unable to update https://github.com/habitat-sh/ipc-channel?branch=hbt-windows#2d085faf
Caused by:
  [4/-3] revspec '2d085faf5bc053fb321e0d375b7328d023ea3436' not found
```

Signed-off-by: Lorenzo Manacorda <lorenzo@kinvolk.io>