add step for sourcing environment to fix make error
Without sourcing, there's no rustc in the PATH:

    root@f28438e09c40:/# cd habitat && make
    sh -c 'cd components/director && cargo build'
        Updating registry `https://github.com/rust-lang/crates.io-index`
        Updating git repository `https://github.com/reset/rust-zmq.git`
        Updating git repository `https://github.com/habitat-sh/redis-rs`
        Updating git repository `https://github.com/habitat-sh/urlencoded.git`
        Updating git repository `https://github.com/habitat-sh/r2d2-redis.git`
    error: An unknown error occurred

    To learn more, run the command again with --verbose.
    Makefile:165: recipe for target 'build-director' failed
    make: *** [build-director] Error 101
    root@f28438e09c40:/habitat# cd components/director && cargo build --verbose
    error: Could not execute process `rustc -vV` (never executed)

    Caused by:
      No such file or directory (os error 2)

Sourcing solves that:

    root@f28438e09c40:/habitat# source $HOME/.cargo/env
    root@f28438e09c40:/habitat# make
    sh -c 'cd components/director && cargo build'
    warning: unused manifest key: package.workspace
        Updating registry `https://github.com/rust-lang/crates.io-index`
        Updating git repository `https://github.com/habitat-sh/redis-rs`
     Downloading log v0.3.6
     Downloading clap v2.13.0
     Downloading env_logger v0.3.5
     Downloading wonder v0.1.0

Also added wget to the list of packages to install for CentOS, otherwise
the wget for cargo-nightly doesn't work.

Signed-off-by: Robb Kidd <robb@thekidds.org>